# Generated by Django 4.2 on 2023-04-25 21:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothing",
            name="image",
            field=models.ImageField(upload_to="clothing"),
        ),
        migrations.AlterField(
            model_name="clothing",
            name="size",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("XXS", "XXS"),
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("нет в наличий", "нет в наличий"),
                ],
                max_length=50,
            ),
        ),
    ]
