# Generated by Django 4.2 on 2023-04-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_clothing_image_alter_clothing_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothing",
            name="image",
            field=models.ImageField(upload_to="test1/clothing"),
        ),
    ]
