# Generated by Django 4.2 on 2023-04-25 21:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_clothing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothing",
            name="image",
            field=models.ImageField(upload_to="main/static/main/clothing"),
        ),
        migrations.AlterField(
            model_name="clothing",
            name="size",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("XXS", "XXS"),
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                ],
                max_length=100,
            ),
        ),
    ]
